<?php

use Kata\Homeworks\H03Cashier\Product;
use Kata\Homeworks\H03Cashier\Apple;
use Kata\Homeworks\H03Cashier\Starship;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-19 at 13:40:13.
 */
class ProductTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::getPriceForCashier
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     * @dataProvider getPriceForCashierDataProvider
     */
    public function testGetPriceForCashier($expectedPrice, Product $product)
    {
        $this->assertEquals($expectedPrice, $product->getPriceForCashier());
    }

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::getAmountForCashier
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     * @dataProvider getAmountForCashierDataProvider
     */
    public function testGetAmountForCashier($expectedAmount, Product $product)
    {
        $this->assertEquals($expectedAmount, $product->getAmountForCashier());
    }

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::getName
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     */
    public function testGetName()
    {
        $apple = new Apple();
        
        $this->assertEquals('Apple', $apple->getName());
    }

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::getAmount
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     */
    public function testGetAmount()
    {
        $apple = new Apple(12);
        
        $this->assertEquals(12, $apple->getName());
    }

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::getDiscount
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     */
    public function testGetDiscount()
    {
        $apple = new Apple();
        $this->assertInstanceOf('\Kata\Homeworks\H03Cashier\DiscountPiece', $apple->getDiscount());
    }

    /**
     * @covers Kata\Homeworks\H03Cashier\Product::setAmount
     * @uses Kata\Homeworks\H03Cashier\Product
     * @uses Kata\Homeworks\H03Cashier\Discount
     */
    public function testSetAmount()
    {
        $apple = new Apple(2);
        $apple->setAmount(5);
        
        $this->assertEquals(7, $apple->getAmount());
    }

    
    /** Data providers */
    
    public function getPriceForCashierDataProvider()
    {
        return array (
            array (32, new Apple(2)),
            array (25, new Apple(5)),
        );
    }
    
    public function getAmountForCashierDataProvider()
    {
        return array (
            array (1, new Starship(1)),
            array (2, new Starship(2)),
            array (2, new Starship(3)),
            array (4, new Starship(5)),
            array (4, new Starship(6)),
        );
    }
}
